service: aws-xray-project
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  tracing:
    lambda: true
    apiGateway: true
  iam:
    role:
      statements: 
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: 
            - '*'
  
functions:
  productsHandler:
    handler: productsHandler.handler
    environment: 
      CURRENCY_API_KEY: ${env:CURRENCY_API_KEY}
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1